---
- include_role:
    name: galaxy/geerlingguy.nginx

- name: Change default template
  template:
    src: "{{ playbook_dir }}/roles/nginx/templates/consul_vhost.conf"
    dest: /etc/nginx/sites-enabled/default
    owner: "{{ deploy_user }}"
    group: wheel
  notify: restart nginx
